"""Cross-language cryptographic parity (PHASE6_PLAN.md §4, §10).

The #1 correctness risk of the Go swap is content-address divergence: if Go's
CBOR or BLAKE3 output differs from Python's by one byte, every hash changes and
the two implementations can't interoperate.

This test runs the Go parity suite (go/pkg/parity/parity_test.go) against the
frozen corpus (tests/parity_vectors.json, generated by
scripts/gen_parity_vectors.py from the Python reference). The Go side must
produce byte-identical CBOR, BLAKE3 multihashes, Ed25519 signatures, and Merkle
roots for every vector.

The discipline is: freeze a corpus and assert byte-equality — do not trust the
libraries.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
GO_DIR = REPO_ROOT / "go"
CORPUS = REPO_ROOT / "tests" / "parity_vectors.json"


def _find_go() -> str | None:
    """Locate the go binary (PATH first, then GOROOT)."""
    go = shutil.which("go")
    if go:
        return go
    goroot = os.environ.get("GOROOT")
    if goroot:
        candidate = Path(goroot) / "bin" / "go"
        if candidate.exists():
            return str(candidate)
    return None


@pytest.mark.skipif(
    _find_go() is None,
    reason="Go toolchain not installed (see PHASE6_PLAN.md §5)",
)
def test_go_parity() -> None:
    """The Go implementation matches the Python reference byte-for-byte."""
    assert CORPUS.exists(), f"corpus missing: {CORPUS} (run scripts/gen_parity_vectors.py)"
    assert GO_DIR.exists(), f"go module missing: {GO_DIR}"

    env = dict(os.environ)
    env["ARXDB_PARITY_CORPUS"] = str(CORPUS)

    result = subprocess.run(
        ["go", "test", "./pkg/parity/", "-v"],
        cwd=GO_DIR,
        env=env,
        capture_output=True,
        text=True,
    )

    # Surface the Go test output on failure so the divergence is visible.
    if result.returncode != 0:
        pytest.fail(
            "Go parity test failed:\n"
            + result.stdout
            + result.stderr
        )
