# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import arxdb_pb2 as arxdb__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in arxdb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StorageServiceStub:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutObject = channel.unary_unary(
                '/arxdb.StorageService/PutObject',
                request_serializer=arxdb__pb2.PutObjectRequest.SerializeToString,
                response_deserializer=arxdb__pb2.PutObjectResponse.FromString,
                _registered_method=True)
        self.GetObject = channel.unary_unary(
                '/arxdb.StorageService/GetObject',
                request_serializer=arxdb__pb2.GetObjectRequest.SerializeToString,
                response_deserializer=arxdb__pb2.GetObjectResponse.FromString,
                _registered_method=True)
        self.HasObject = channel.unary_unary(
                '/arxdb.StorageService/HasObject',
                request_serializer=arxdb__pb2.HasObjectRequest.SerializeToString,
                response_deserializer=arxdb__pb2.HasObjectResponse.FromString,
                _registered_method=True)
        self.RegisterNode = channel.unary_unary(
                '/arxdb.StorageService/RegisterNode',
                request_serializer=arxdb__pb2.RegisterNodeRequest.SerializeToString,
                response_deserializer=arxdb__pb2.RegisterNodeResponse.FromString,
                _registered_method=True)
        self.RegisterEdge = channel.unary_unary(
                '/arxdb.StorageService/RegisterEdge',
                request_serializer=arxdb__pb2.RegisterEdgeRequest.SerializeToString,
                response_deserializer=arxdb__pb2.RegisterEdgeResponse.FromString,
                _registered_method=True)
        self.GetConnectivity = channel.unary_unary(
                '/arxdb.StorageService/GetConnectivity',
                request_serializer=arxdb__pb2.GetConnectivityRequest.SerializeToString,
                response_deserializer=arxdb__pb2.GetConnectivityResponse.FromString,
                _registered_method=True)
        self.IncomingEdges = channel.unary_unary(
                '/arxdb.StorageService/IncomingEdges',
                request_serializer=arxdb__pb2.IncomingEdgesRequest.SerializeToString,
                response_deserializer=arxdb__pb2.IncomingEdgesResponse.FromString,
                _registered_method=True)
        self.OutgoingEdges = channel.unary_unary(
                '/arxdb.StorageService/OutgoingEdges',
                request_serializer=arxdb__pb2.OutgoingEdgesRequest.SerializeToString,
                response_deserializer=arxdb__pb2.OutgoingEdgesResponse.FromString,
                _registered_method=True)
        self.AllNodes = channel.unary_unary(
                '/arxdb.StorageService/AllNodes',
                request_serializer=arxdb__pb2.AllNodesRequest.SerializeToString,
                response_deserializer=arxdb__pb2.AllNodesResponse.FromString,
                _registered_method=True)
        self.AllEdges = channel.unary_unary(
                '/arxdb.StorageService/AllEdges',
                request_serializer=arxdb__pb2.AllEdgesRequest.SerializeToString,
                response_deserializer=arxdb__pb2.AllEdgesResponse.FromString,
                _registered_method=True)
        self.Append = channel.unary_unary(
                '/arxdb.StorageService/Append',
                request_serializer=arxdb__pb2.AppendRequest.SerializeToString,
                response_deserializer=arxdb__pb2.AppendResponse.FromString,
                _registered_method=True)
        self.GetEntry = channel.unary_unary(
                '/arxdb.StorageService/GetEntry',
                request_serializer=arxdb__pb2.GetEntryRequest.SerializeToString,
                response_deserializer=arxdb__pb2.GetEntryResponse.FromString,
                _registered_method=True)
        self.RootHash = channel.unary_unary(
                '/arxdb.StorageService/RootHash',
                request_serializer=arxdb__pb2.RootHashRequest.SerializeToString,
                response_deserializer=arxdb__pb2.RootHashResponse.FromString,
                _registered_method=True)
        self.InclusionProof = channel.unary_unary(
                '/arxdb.StorageService/InclusionProof',
                request_serializer=arxdb__pb2.InclusionProofRequest.SerializeToString,
                response_deserializer=arxdb__pb2.InclusionProofResponse.FromString,
                _registered_method=True)
        self.Len = channel.unary_unary(
                '/arxdb.StorageService/Len',
                request_serializer=arxdb__pb2.LenRequest.SerializeToString,
                response_deserializer=arxdb__pb2.LenResponse.FromString,
                _registered_method=True)
        self.CommitEdge = channel.unary_unary(
                '/arxdb.StorageService/CommitEdge',
                request_serializer=arxdb__pb2.CommitEdgeRequest.SerializeToString,
                response_deserializer=arxdb__pb2.CommitEdgeResponse.FromString,
                _registered_method=True)


class StorageServiceServicer:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def PutObject(self, request, context):
        """Object store
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HasObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterNode(self, request, context):
        """Graph index
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnectivity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncomingEdges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OutgoingEdges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllEdges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Append(self, request, context):
        """Append log
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RootHash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InclusionProof(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Len(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitEdge(self, request, context):
        """Atomic commit
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutObject': grpc.unary_unary_rpc_method_handler(
                    servicer.PutObject,
                    request_deserializer=arxdb__pb2.PutObjectRequest.FromString,
                    response_serializer=arxdb__pb2.PutObjectResponse.SerializeToString,
            ),
            'GetObject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObject,
                    request_deserializer=arxdb__pb2.GetObjectRequest.FromString,
                    response_serializer=arxdb__pb2.GetObjectResponse.SerializeToString,
            ),
            'HasObject': grpc.unary_unary_rpc_method_handler(
                    servicer.HasObject,
                    request_deserializer=arxdb__pb2.HasObjectRequest.FromString,
                    response_serializer=arxdb__pb2.HasObjectResponse.SerializeToString,
            ),
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=arxdb__pb2.RegisterNodeRequest.FromString,
                    response_serializer=arxdb__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'RegisterEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterEdge,
                    request_deserializer=arxdb__pb2.RegisterEdgeRequest.FromString,
                    response_serializer=arxdb__pb2.RegisterEdgeResponse.SerializeToString,
            ),
            'GetConnectivity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnectivity,
                    request_deserializer=arxdb__pb2.GetConnectivityRequest.FromString,
                    response_serializer=arxdb__pb2.GetConnectivityResponse.SerializeToString,
            ),
            'IncomingEdges': grpc.unary_unary_rpc_method_handler(
                    servicer.IncomingEdges,
                    request_deserializer=arxdb__pb2.IncomingEdgesRequest.FromString,
                    response_serializer=arxdb__pb2.IncomingEdgesResponse.SerializeToString,
            ),
            'OutgoingEdges': grpc.unary_unary_rpc_method_handler(
                    servicer.OutgoingEdges,
                    request_deserializer=arxdb__pb2.OutgoingEdgesRequest.FromString,
                    response_serializer=arxdb__pb2.OutgoingEdgesResponse.SerializeToString,
            ),
            'AllNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.AllNodes,
                    request_deserializer=arxdb__pb2.AllNodesRequest.FromString,
                    response_serializer=arxdb__pb2.AllNodesResponse.SerializeToString,
            ),
            'AllEdges': grpc.unary_unary_rpc_method_handler(
                    servicer.AllEdges,
                    request_deserializer=arxdb__pb2.AllEdgesRequest.FromString,
                    response_serializer=arxdb__pb2.AllEdgesResponse.SerializeToString,
            ),
            'Append': grpc.unary_unary_rpc_method_handler(
                    servicer.Append,
                    request_deserializer=arxdb__pb2.AppendRequest.FromString,
                    response_serializer=arxdb__pb2.AppendResponse.SerializeToString,
            ),
            'GetEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntry,
                    request_deserializer=arxdb__pb2.GetEntryRequest.FromString,
                    response_serializer=arxdb__pb2.GetEntryResponse.SerializeToString,
            ),
            'RootHash': grpc.unary_unary_rpc_method_handler(
                    servicer.RootHash,
                    request_deserializer=arxdb__pb2.RootHashRequest.FromString,
                    response_serializer=arxdb__pb2.RootHashResponse.SerializeToString,
            ),
            'InclusionProof': grpc.unary_unary_rpc_method_handler(
                    servicer.InclusionProof,
                    request_deserializer=arxdb__pb2.InclusionProofRequest.FromString,
                    response_serializer=arxdb__pb2.InclusionProofResponse.SerializeToString,
            ),
            'Len': grpc.unary_unary_rpc_method_handler(
                    servicer.Len,
                    request_deserializer=arxdb__pb2.LenRequest.FromString,
                    response_serializer=arxdb__pb2.LenResponse.SerializeToString,
            ),
            'CommitEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitEdge,
                    request_deserializer=arxdb__pb2.CommitEdgeRequest.FromString,
                    response_serializer=arxdb__pb2.CommitEdgeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arxdb.StorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arxdb.StorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageService:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def PutObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arxdb.StorageService/PutObject',
            arxdb__pb2.PutObjectRequest.SerializeToString,
            arxdb__pb2.PutObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arxdb.StorageService/GetObject',
            arxdb__pb2.GetObjectRequest.SerializeToString,
            arxdb__pb2.GetObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HasObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arxdb.StorageService/HasObject',
            arxdb__pb2.HasObjectRequest.SerializeToString,
            arxdb__pb2.HasObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arxdb.StorageService/RegisterNode',
            arxdb__pb2.RegisterNodeRequest.SerializeToString,
            arxdb__pb2.RegisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arxdb.StorageService/RegisterEdge',
            arxdb__pb2.RegisterEdgeRequest.SerializeToString,
            arxdb__pb2.RegisterEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConnectivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arxdb.StorageService/GetConnectivity',
            arxdb__pb2.GetConnectivityRequest.SerializeToString,
            arxdb__pb2.GetConnectivityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IncomingEdges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arxdb.StorageService/IncomingEdges',
            arxdb__pb2.IncomingEdgesRequest.SerializeToString,
            arxdb__pb2.IncomingEdgesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OutgoingEdges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arxdb.StorageService/OutgoingEdges',
            arxdb__pb2.OutgoingEdgesRequest.SerializeToString,
            arxdb__pb2.OutgoingEdgesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arxdb.StorageService/AllNodes',
            arxdb__pb2.AllNodesRequest.SerializeToString,
            arxdb__pb2.AllNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllEdges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arxdb.StorageService/AllEdges',
            arxdb__pb2.AllEdgesRequest.SerializeToString,
            arxdb__pb2.AllEdgesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Append(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arxdb.StorageService/Append',
            arxdb__pb2.AppendRequest.SerializeToString,
            arxdb__pb2.AppendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arxdb.StorageService/GetEntry',
            arxdb__pb2.GetEntryRequest.SerializeToString,
            arxdb__pb2.GetEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RootHash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arxdb.StorageService/RootHash',
            arxdb__pb2.RootHashRequest.SerializeToString,
            arxdb__pb2.RootHashResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InclusionProof(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arxdb.StorageService/InclusionProof',
            arxdb__pb2.InclusionProofRequest.SerializeToString,
            arxdb__pb2.InclusionProofResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Len(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arxdb.StorageService/Len',
            arxdb__pb2.LenRequest.SerializeToString,
            arxdb__pb2.LenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arxdb.StorageService/CommitEdge',
            arxdb__pb2.CommitEdgeRequest.SerializeToString,
            arxdb__pb2.CommitEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
