// ArxDB StorageService — the language-agnostic storage contract.
//
// This is the process-boundary form of STORAGE_API.md. The Go daemon
// (cmd/arxdbd) implements this service over gRPC; the Python verification
// layer talks to it through src/arxdb/storage/grpc_client.py, which presents
// the *same* Storage interface as the in-process SQLite backend.
//
// All hashes are 34-byte BLAKE3 multihashes (0x1e || 0x20 || 32-byte digest),
// carried as `bytes`. The daemon owns the storage engine and the signing
// keypair; clients do not pass keys or roots per-call.
//
// Scope (Phase 6, Scope A): storage-only. The two semantic queries
// (reachable / path_discovery) deliberately live in the Python query layer,
// not here — see STORAGE_API.md "Deliberately absent".

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: proto/arxdb.proto

package arxdbpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageService_PutObject_FullMethodName       = "/arxdb.StorageService/PutObject"
	StorageService_GetObject_FullMethodName       = "/arxdb.StorageService/GetObject"
	StorageService_HasObject_FullMethodName       = "/arxdb.StorageService/HasObject"
	StorageService_RegisterNode_FullMethodName    = "/arxdb.StorageService/RegisterNode"
	StorageService_RegisterEdge_FullMethodName    = "/arxdb.StorageService/RegisterEdge"
	StorageService_GetConnectivity_FullMethodName = "/arxdb.StorageService/GetConnectivity"
	StorageService_IncomingEdges_FullMethodName   = "/arxdb.StorageService/IncomingEdges"
	StorageService_OutgoingEdges_FullMethodName   = "/arxdb.StorageService/OutgoingEdges"
	StorageService_AllNodes_FullMethodName        = "/arxdb.StorageService/AllNodes"
	StorageService_AllEdges_FullMethodName        = "/arxdb.StorageService/AllEdges"
	StorageService_Append_FullMethodName          = "/arxdb.StorageService/Append"
	StorageService_GetEntry_FullMethodName        = "/arxdb.StorageService/GetEntry"
	StorageService_RootHash_FullMethodName        = "/arxdb.StorageService/RootHash"
	StorageService_InclusionProof_FullMethodName  = "/arxdb.StorageService/InclusionProof"
	StorageService_Len_FullMethodName             = "/arxdb.StorageService/Len"
	StorageService_CommitEdge_FullMethodName      = "/arxdb.StorageService/CommitEdge"
)

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageServiceClient interface {
	// Object store
	PutObject(ctx context.Context, in *PutObjectRequest, opts ...grpc.CallOption) (*PutObjectResponse, error)
	GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error)
	HasObject(ctx context.Context, in *HasObjectRequest, opts ...grpc.CallOption) (*HasObjectResponse, error)
	// Graph index
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	RegisterEdge(ctx context.Context, in *RegisterEdgeRequest, opts ...grpc.CallOption) (*RegisterEdgeResponse, error)
	GetConnectivity(ctx context.Context, in *GetConnectivityRequest, opts ...grpc.CallOption) (*GetConnectivityResponse, error)
	IncomingEdges(ctx context.Context, in *IncomingEdgesRequest, opts ...grpc.CallOption) (*IncomingEdgesResponse, error)
	OutgoingEdges(ctx context.Context, in *OutgoingEdgesRequest, opts ...grpc.CallOption) (*OutgoingEdgesResponse, error)
	AllNodes(ctx context.Context, in *AllNodesRequest, opts ...grpc.CallOption) (*AllNodesResponse, error)
	AllEdges(ctx context.Context, in *AllEdgesRequest, opts ...grpc.CallOption) (*AllEdgesResponse, error)
	// Append log
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error)
	GetEntry(ctx context.Context, in *GetEntryRequest, opts ...grpc.CallOption) (*GetEntryResponse, error)
	RootHash(ctx context.Context, in *RootHashRequest, opts ...grpc.CallOption) (*RootHashResponse, error)
	InclusionProof(ctx context.Context, in *InclusionProofRequest, opts ...grpc.CallOption) (*InclusionProofResponse, error)
	Len(ctx context.Context, in *LenRequest, opts ...grpc.CallOption) (*LenResponse, error)
	// Atomic commit
	CommitEdge(ctx context.Context, in *CommitEdgeRequest, opts ...grpc.CallOption) (*CommitEdgeResponse, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) PutObject(ctx context.Context, in *PutObjectRequest, opts ...grpc.CallOption) (*PutObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutObjectResponse)
	err := c.cc.Invoke(ctx, StorageService_PutObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObjectResponse)
	err := c.cc.Invoke(ctx, StorageService_GetObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) HasObject(ctx context.Context, in *HasObjectRequest, opts ...grpc.CallOption) (*HasObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasObjectResponse)
	err := c.cc.Invoke(ctx, StorageService_HasObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, StorageService_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) RegisterEdge(ctx context.Context, in *RegisterEdgeRequest, opts ...grpc.CallOption) (*RegisterEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterEdgeResponse)
	err := c.cc.Invoke(ctx, StorageService_RegisterEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetConnectivity(ctx context.Context, in *GetConnectivityRequest, opts ...grpc.CallOption) (*GetConnectivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectivityResponse)
	err := c.cc.Invoke(ctx, StorageService_GetConnectivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) IncomingEdges(ctx context.Context, in *IncomingEdgesRequest, opts ...grpc.CallOption) (*IncomingEdgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncomingEdgesResponse)
	err := c.cc.Invoke(ctx, StorageService_IncomingEdges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) OutgoingEdges(ctx context.Context, in *OutgoingEdgesRequest, opts ...grpc.CallOption) (*OutgoingEdgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OutgoingEdgesResponse)
	err := c.cc.Invoke(ctx, StorageService_OutgoingEdges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) AllNodes(ctx context.Context, in *AllNodesRequest, opts ...grpc.CallOption) (*AllNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllNodesResponse)
	err := c.cc.Invoke(ctx, StorageService_AllNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) AllEdges(ctx context.Context, in *AllEdgesRequest, opts ...grpc.CallOption) (*AllEdgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllEdgesResponse)
	err := c.cc.Invoke(ctx, StorageService_AllEdges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendResponse)
	err := c.cc.Invoke(ctx, StorageService_Append_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetEntry(ctx context.Context, in *GetEntryRequest, opts ...grpc.CallOption) (*GetEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntryResponse)
	err := c.cc.Invoke(ctx, StorageService_GetEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) RootHash(ctx context.Context, in *RootHashRequest, opts ...grpc.CallOption) (*RootHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RootHashResponse)
	err := c.cc.Invoke(ctx, StorageService_RootHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) InclusionProof(ctx context.Context, in *InclusionProofRequest, opts ...grpc.CallOption) (*InclusionProofResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InclusionProofResponse)
	err := c.cc.Invoke(ctx, StorageService_InclusionProof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) Len(ctx context.Context, in *LenRequest, opts ...grpc.CallOption) (*LenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LenResponse)
	err := c.cc.Invoke(ctx, StorageService_Len_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) CommitEdge(ctx context.Context, in *CommitEdgeRequest, opts ...grpc.CallOption) (*CommitEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitEdgeResponse)
	err := c.cc.Invoke(ctx, StorageService_CommitEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
// All implementations must embed UnimplementedStorageServiceServer
// for forward compatibility.
type StorageServiceServer interface {
	// Object store
	PutObject(context.Context, *PutObjectRequest) (*PutObjectResponse, error)
	GetObject(context.Context, *GetObjectRequest) (*GetObjectResponse, error)
	HasObject(context.Context, *HasObjectRequest) (*HasObjectResponse, error)
	// Graph index
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	RegisterEdge(context.Context, *RegisterEdgeRequest) (*RegisterEdgeResponse, error)
	GetConnectivity(context.Context, *GetConnectivityRequest) (*GetConnectivityResponse, error)
	IncomingEdges(context.Context, *IncomingEdgesRequest) (*IncomingEdgesResponse, error)
	OutgoingEdges(context.Context, *OutgoingEdgesRequest) (*OutgoingEdgesResponse, error)
	AllNodes(context.Context, *AllNodesRequest) (*AllNodesResponse, error)
	AllEdges(context.Context, *AllEdgesRequest) (*AllEdgesResponse, error)
	// Append log
	Append(context.Context, *AppendRequest) (*AppendResponse, error)
	GetEntry(context.Context, *GetEntryRequest) (*GetEntryResponse, error)
	RootHash(context.Context, *RootHashRequest) (*RootHashResponse, error)
	InclusionProof(context.Context, *InclusionProofRequest) (*InclusionProofResponse, error)
	Len(context.Context, *LenRequest) (*LenResponse, error)
	// Atomic commit
	CommitEdge(context.Context, *CommitEdgeRequest) (*CommitEdgeResponse, error)
	mustEmbedUnimplementedStorageServiceServer()
}

// UnimplementedStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageServiceServer struct{}

func (UnimplementedStorageServiceServer) PutObject(context.Context, *PutObjectRequest) (*PutObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutObject not implemented")
}
func (UnimplementedStorageServiceServer) GetObject(context.Context, *GetObjectRequest) (*GetObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObject not implemented")
}
func (UnimplementedStorageServiceServer) HasObject(context.Context, *HasObjectRequest) (*HasObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HasObject not implemented")
}
func (UnimplementedStorageServiceServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedStorageServiceServer) RegisterEdge(context.Context, *RegisterEdgeRequest) (*RegisterEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterEdge not implemented")
}
func (UnimplementedStorageServiceServer) GetConnectivity(context.Context, *GetConnectivityRequest) (*GetConnectivityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnectivity not implemented")
}
func (UnimplementedStorageServiceServer) IncomingEdges(context.Context, *IncomingEdgesRequest) (*IncomingEdgesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IncomingEdges not implemented")
}
func (UnimplementedStorageServiceServer) OutgoingEdges(context.Context, *OutgoingEdgesRequest) (*OutgoingEdgesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OutgoingEdges not implemented")
}
func (UnimplementedStorageServiceServer) AllNodes(context.Context, *AllNodesRequest) (*AllNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllNodes not implemented")
}
func (UnimplementedStorageServiceServer) AllEdges(context.Context, *AllEdgesRequest) (*AllEdgesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllEdges not implemented")
}
func (UnimplementedStorageServiceServer) Append(context.Context, *AppendRequest) (*AppendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedStorageServiceServer) GetEntry(context.Context, *GetEntryRequest) (*GetEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntry not implemented")
}
func (UnimplementedStorageServiceServer) RootHash(context.Context, *RootHashRequest) (*RootHashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RootHash not implemented")
}
func (UnimplementedStorageServiceServer) InclusionProof(context.Context, *InclusionProofRequest) (*InclusionProofResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InclusionProof not implemented")
}
func (UnimplementedStorageServiceServer) Len(context.Context, *LenRequest) (*LenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Len not implemented")
}
func (UnimplementedStorageServiceServer) CommitEdge(context.Context, *CommitEdgeRequest) (*CommitEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitEdge not implemented")
}
func (UnimplementedStorageServiceServer) mustEmbedUnimplementedStorageServiceServer() {}
func (UnimplementedStorageServiceServer) testEmbeddedByValue()                        {}

// UnsafeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServiceServer will
// result in compilation errors.
type UnsafeStorageServiceServer interface {
	mustEmbedUnimplementedStorageServiceServer()
}

func RegisterStorageServiceServer(s grpc.ServiceRegistrar, srv StorageServiceServer) {
	// If the following call panics, it indicates UnimplementedStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageService_ServiceDesc, srv)
}

func _StorageService_PutObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).PutObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_PutObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).PutObject(ctx, req.(*PutObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetObject(ctx, req.(*GetObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_HasObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).HasObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_HasObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).HasObject(ctx, req.(*HasObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_RegisterEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).RegisterEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_RegisterEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).RegisterEdge(ctx, req.(*RegisterEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetConnectivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetConnectivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetConnectivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetConnectivity(ctx, req.(*GetConnectivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_IncomingEdges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncomingEdgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).IncomingEdges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_IncomingEdges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).IncomingEdges(ctx, req.(*IncomingEdgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_OutgoingEdges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutgoingEdgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).OutgoingEdges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_OutgoingEdges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).OutgoingEdges(ctx, req.(*OutgoingEdgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_AllNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).AllNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_AllNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).AllNodes(ctx, req.(*AllNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_AllEdges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllEdgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).AllEdges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_AllEdges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).AllEdges(ctx, req.(*AllEdgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_Append_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetEntry(ctx, req.(*GetEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_RootHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RootHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).RootHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_RootHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).RootHash(ctx, req.(*RootHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_InclusionProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InclusionProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).InclusionProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_InclusionProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).InclusionProof(ctx, req.(*InclusionProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_Len_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).Len(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_Len_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).Len(ctx, req.(*LenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_CommitEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CommitEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_CommitEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CommitEdge(ctx, req.(*CommitEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageService_ServiceDesc is the grpc.ServiceDesc for StorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arxdb.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutObject",
			Handler:    _StorageService_PutObject_Handler,
		},
		{
			MethodName: "GetObject",
			Handler:    _StorageService_GetObject_Handler,
		},
		{
			MethodName: "HasObject",
			Handler:    _StorageService_HasObject_Handler,
		},
		{
			MethodName: "RegisterNode",
			Handler:    _StorageService_RegisterNode_Handler,
		},
		{
			MethodName: "RegisterEdge",
			Handler:    _StorageService_RegisterEdge_Handler,
		},
		{
			MethodName: "GetConnectivity",
			Handler:    _StorageService_GetConnectivity_Handler,
		},
		{
			MethodName: "IncomingEdges",
			Handler:    _StorageService_IncomingEdges_Handler,
		},
		{
			MethodName: "OutgoingEdges",
			Handler:    _StorageService_OutgoingEdges_Handler,
		},
		{
			MethodName: "AllNodes",
			Handler:    _StorageService_AllNodes_Handler,
		},
		{
			MethodName: "AllEdges",
			Handler:    _StorageService_AllEdges_Handler,
		},
		{
			MethodName: "Append",
			Handler:    _StorageService_Append_Handler,
		},
		{
			MethodName: "GetEntry",
			Handler:    _StorageService_GetEntry_Handler,
		},
		{
			MethodName: "RootHash",
			Handler:    _StorageService_RootHash_Handler,
		},
		{
			MethodName: "InclusionProof",
			Handler:    _StorageService_InclusionProof_Handler,
		},
		{
			MethodName: "Len",
			Handler:    _StorageService_Len_Handler,
		},
		{
			MethodName: "CommitEdge",
			Handler:    _StorageService_CommitEdge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/arxdb.proto",
}
