// ArxDB StorageService — the language-agnostic storage contract.
//
// This is the process-boundary form of STORAGE_API.md. The Go daemon
// (cmd/arxdbd) implements this service over gRPC; the Python verification
// layer talks to it through src/arxdb/storage/grpc_client.py, which presents
// the *same* Storage interface as the in-process SQLite backend.
//
// All hashes are 34-byte BLAKE3 multihashes (0x1e || 0x20 || 32-byte digest),
// carried as `bytes`. The daemon owns the storage engine and the signing
// keypair; clients do not pass keys or roots per-call.
//
// Scope (Phase 6, Scope A): storage-only. The two semantic queries
// (reachable / path_discovery) deliberately live in the Python query layer,
// not here — see STORAGE_API.md "Deliberately absent".

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/arxdb.proto

package arxdbpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          [][]byte               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"` // blobs to store
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutObjectRequest) Reset() {
	*x = PutObjectRequest{}
	mi := &file_proto_arxdb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutObjectRequest) ProtoMessage() {}

func (x *PutObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutObjectRequest.ProtoReflect.Descriptor instead.
func (*PutObjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{0}
}

func (x *PutObjectRequest) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        [][]byte               `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"` // content hashes, parallel to data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutObjectResponse) Reset() {
	*x = PutObjectResponse{}
	mi := &file_proto_arxdb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutObjectResponse) ProtoMessage() {}

func (x *PutObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutObjectResponse.ProtoReflect.Descriptor instead.
func (*PutObjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{1}
}

func (x *PutObjectResponse) GetHashes() [][]byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type GetObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        [][]byte               `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectRequest) Reset() {
	*x = GetObjectRequest{}
	mi := &file_proto_arxdb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectRequest) ProtoMessage() {}

func (x *GetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectRequest.ProtoReflect.Descriptor instead.
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{2}
}

func (x *GetObjectRequest) GetHashes() [][]byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type GetObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          [][]byte               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`           // blob bytes; empty where found == false
	Found         []bool                 `protobuf:"varint,2,rep,packed,name=found,proto3" json:"found,omitempty"` // parallel to hashes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectResponse) Reset() {
	*x = GetObjectResponse{}
	mi := &file_proto_arxdb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectResponse) ProtoMessage() {}

func (x *GetObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectResponse.ProtoReflect.Descriptor instead.
func (*GetObjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{3}
}

func (x *GetObjectResponse) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetObjectResponse) GetFound() []bool {
	if x != nil {
		return x.Found
	}
	return nil
}

type HasObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        [][]byte               `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasObjectRequest) Reset() {
	*x = HasObjectRequest{}
	mi := &file_proto_arxdb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasObjectRequest) ProtoMessage() {}

func (x *HasObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasObjectRequest.ProtoReflect.Descriptor instead.
func (*HasObjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{4}
}

func (x *HasObjectRequest) GetHashes() [][]byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type HasObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         []bool                 `protobuf:"varint,1,rep,packed,name=found,proto3" json:"found,omitempty"` // parallel to hashes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasObjectResponse) Reset() {
	*x = HasObjectResponse{}
	mi := &file_proto_arxdb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasObjectResponse) ProtoMessage() {}

func (x *HasObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasObjectResponse.ProtoReflect.Descriptor instead.
func (*HasObjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{5}
}

func (x *HasObjectResponse) GetFound() []bool {
	if x != nil {
		return x.Found
	}
	return nil
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeHash      []byte                 `protobuf:"bytes,1,opt,name=node_hash,json=nodeHash,proto3" json:"node_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_proto_arxdb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterNodeRequest) GetNodeHash() []byte {
	if x != nil {
		return x.NodeHash
	}
	return nil
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_proto_arxdb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{7}
}

type RegisterEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeHash      []byte                 `protobuf:"bytes,1,opt,name=edge_hash,json=edgeHash,proto3" json:"edge_hash,omitempty"`
	Premises      [][]byte               `protobuf:"bytes,2,rep,name=premises,proto3" json:"premises,omitempty"`
	Conclusion    []byte                 `protobuf:"bytes,3,opt,name=conclusion,proto3" json:"conclusion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterEdgeRequest) Reset() {
	*x = RegisterEdgeRequest{}
	mi := &file_proto_arxdb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEdgeRequest) ProtoMessage() {}

func (x *RegisterEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEdgeRequest.ProtoReflect.Descriptor instead.
func (*RegisterEdgeRequest) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterEdgeRequest) GetEdgeHash() []byte {
	if x != nil {
		return x.EdgeHash
	}
	return nil
}

func (x *RegisterEdgeRequest) GetPremises() [][]byte {
	if x != nil {
		return x.Premises
	}
	return nil
}

func (x *RegisterEdgeRequest) GetConclusion() []byte {
	if x != nil {
		return x.Conclusion
	}
	return nil
}

type RegisterEdgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterEdgeResponse) Reset() {
	*x = RegisterEdgeResponse{}
	mi := &file_proto_arxdb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEdgeResponse) ProtoMessage() {}

func (x *RegisterEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEdgeResponse.ProtoReflect.Descriptor instead.
func (*RegisterEdgeResponse) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{9}
}

type GetConnectivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeHash      []byte                 `protobuf:"bytes,1,opt,name=edge_hash,json=edgeHash,proto3" json:"edge_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectivityRequest) Reset() {
	*x = GetConnectivityRequest{}
	mi := &file_proto_arxdb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectivityRequest) ProtoMessage() {}

func (x *GetConnectivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectivityRequest.ProtoReflect.Descriptor instead.
func (*GetConnectivityRequest) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{10}
}

func (x *GetConnectivityRequest) GetEdgeHash() []byte {
	if x != nil {
		return x.EdgeHash
	}
	return nil
}

type GetConnectivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Premises      [][]byte               `protobuf:"bytes,1,rep,name=premises,proto3" json:"premises,omitempty"`
	Conclusion    []byte                 `protobuf:"bytes,2,opt,name=conclusion,proto3" json:"conclusion,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectivityResponse) Reset() {
	*x = GetConnectivityResponse{}
	mi := &file_proto_arxdb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectivityResponse) ProtoMessage() {}

func (x *GetConnectivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectivityResponse.ProtoReflect.Descriptor instead.
func (*GetConnectivityResponse) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{11}
}

func (x *GetConnectivityResponse) GetPremises() [][]byte {
	if x != nil {
		return x.Premises
	}
	return nil
}

func (x *GetConnectivityResponse) GetConclusion() []byte {
	if x != nil {
		return x.Conclusion
	}
	return nil
}

func (x *GetConnectivityResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type IncomingEdgesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeHash      []byte                 `protobuf:"bytes,1,opt,name=node_hash,json=nodeHash,proto3" json:"node_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomingEdgesRequest) Reset() {
	*x = IncomingEdgesRequest{}
	mi := &file_proto_arxdb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingEdgesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingEdgesRequest) ProtoMessage() {}

func (x *IncomingEdgesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingEdgesRequest.ProtoReflect.Descriptor instead.
func (*IncomingEdgesRequest) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{12}
}

func (x *IncomingEdgesRequest) GetNodeHash() []byte {
	if x != nil {
		return x.NodeHash
	}
	return nil
}

type IncomingEdgesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeHashes    [][]byte               `protobuf:"bytes,1,rep,name=edge_hashes,json=edgeHashes,proto3" json:"edge_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomingEdgesResponse) Reset() {
	*x = IncomingEdgesResponse{}
	mi := &file_proto_arxdb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingEdgesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingEdgesResponse) ProtoMessage() {}

func (x *IncomingEdgesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingEdgesResponse.ProtoReflect.Descriptor instead.
func (*IncomingEdgesResponse) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{13}
}

func (x *IncomingEdgesResponse) GetEdgeHashes() [][]byte {
	if x != nil {
		return x.EdgeHashes
	}
	return nil
}

type OutgoingEdgesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeHash      []byte                 `protobuf:"bytes,1,opt,name=node_hash,json=nodeHash,proto3" json:"node_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutgoingEdgesRequest) Reset() {
	*x = OutgoingEdgesRequest{}
	mi := &file_proto_arxdb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutgoingEdgesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutgoingEdgesRequest) ProtoMessage() {}

func (x *OutgoingEdgesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutgoingEdgesRequest.ProtoReflect.Descriptor instead.
func (*OutgoingEdgesRequest) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{14}
}

func (x *OutgoingEdgesRequest) GetNodeHash() []byte {
	if x != nil {
		return x.NodeHash
	}
	return nil
}

type OutgoingEdgesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeHashes    [][]byte               `protobuf:"bytes,1,rep,name=edge_hashes,json=edgeHashes,proto3" json:"edge_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutgoingEdgesResponse) Reset() {
	*x = OutgoingEdgesResponse{}
	mi := &file_proto_arxdb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutgoingEdgesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutgoingEdgesResponse) ProtoMessage() {}

func (x *OutgoingEdgesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutgoingEdgesResponse.ProtoReflect.Descriptor instead.
func (*OutgoingEdgesResponse) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{15}
}

func (x *OutgoingEdgesResponse) GetEdgeHashes() [][]byte {
	if x != nil {
		return x.EdgeHashes
	}
	return nil
}

type AllNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllNodesRequest) Reset() {
	*x = AllNodesRequest{}
	mi := &file_proto_arxdb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllNodesRequest) ProtoMessage() {}

func (x *AllNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllNodesRequest.ProtoReflect.Descriptor instead.
func (*AllNodesRequest) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{16}
}

type AllNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeHashes    [][]byte               `protobuf:"bytes,1,rep,name=node_hashes,json=nodeHashes,proto3" json:"node_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllNodesResponse) Reset() {
	*x = AllNodesResponse{}
	mi := &file_proto_arxdb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllNodesResponse) ProtoMessage() {}

func (x *AllNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllNodesResponse.ProtoReflect.Descriptor instead.
func (*AllNodesResponse) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{17}
}

func (x *AllNodesResponse) GetNodeHashes() [][]byte {
	if x != nil {
		return x.NodeHashes
	}
	return nil
}

type AllEdgesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllEdgesRequest) Reset() {
	*x = AllEdgesRequest{}
	mi := &file_proto_arxdb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllEdgesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllEdgesRequest) ProtoMessage() {}

func (x *AllEdgesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllEdgesRequest.ProtoReflect.Descriptor instead.
func (*AllEdgesRequest) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{18}
}

type AllEdgesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeHashes    [][]byte               `protobuf:"bytes,1,rep,name=edge_hashes,json=edgeHashes,proto3" json:"edge_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllEdgesResponse) Reset() {
	*x = AllEdgesResponse{}
	mi := &file_proto_arxdb_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllEdgesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllEdgesResponse) ProtoMessage() {}

func (x *AllEdgesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllEdgesResponse.ProtoReflect.Descriptor instead.
func (*AllEdgesResponse) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{19}
}

func (x *AllEdgesResponse) GetEdgeHashes() [][]byte {
	if x != nil {
		return x.EdgeHashes
	}
	return nil
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	SignerPubkey  []byte                 `protobuf:"bytes,3,opt,name=signer_pubkey,json=signerPubkey,proto3" json:"signer_pubkey,omitempty"`
	EntryHash     []byte                 `protobuf:"bytes,4,opt,name=entry_hash,json=entryHash,proto3" json:"entry_hash,omitempty"` // content hash of payload
	PrevLogHash   []byte                 `protobuf:"bytes,5,opt,name=prev_log_hash,json=prevLogHash,proto3" json:"prev_log_hash,omitempty"`
	Signature     []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"` // over canonical_encode([seq, ts, pubkey, entry_hash, prev_log_hash])
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_arxdb_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{20}
}

func (x *LogEntry) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *LogEntry) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *LogEntry) GetSignerPubkey() []byte {
	if x != nil {
		return x.SignerPubkey
	}
	return nil
}

func (x *LogEntry) GetEntryHash() []byte {
	if x != nil {
		return x.EntryHash
	}
	return nil
}

func (x *LogEntry) GetPrevLogHash() []byte {
	if x != nil {
		return x.PrevLogHash
	}
	return nil
}

func (x *LogEntry) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *LogEntry) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type AppendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         []byte                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"` // raw entry bytes; the daemon signs internally
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_proto_arxdb_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{21}
}

func (x *AppendRequest) GetEntry() []byte {
	if x != nil {
		return x.Entry
	}
	return nil
}

type AppendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *LogEntry              `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_proto_arxdb_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{22}
}

func (x *AppendResponse) GetEntry() *LogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type GetEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntryRequest) Reset() {
	*x = GetEntryRequest{}
	mi := &file_proto_arxdb_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryRequest) ProtoMessage() {}

func (x *GetEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryRequest.ProtoReflect.Descriptor instead.
func (*GetEntryRequest) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{23}
}

func (x *GetEntryRequest) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type GetEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *LogEntry              `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntryResponse) Reset() {
	*x = GetEntryResponse{}
	mi := &file_proto_arxdb_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryResponse) ProtoMessage() {}

func (x *GetEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryResponse.ProtoReflect.Descriptor instead.
func (*GetEntryResponse) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{24}
}

func (x *GetEntryResponse) GetEntry() *LogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *GetEntryResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type RootHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootHashRequest) Reset() {
	*x = RootHashRequest{}
	mi := &file_proto_arxdb_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootHashRequest) ProtoMessage() {}

func (x *RootHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootHashRequest.ProtoReflect.Descriptor instead.
func (*RootHashRequest) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{25}
}

type RootHashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootHash      []byte                 `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootHashResponse) Reset() {
	*x = RootHashResponse{}
	mi := &file_proto_arxdb_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootHashResponse) ProtoMessage() {}

func (x *RootHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootHashResponse.ProtoReflect.Descriptor instead.
func (*RootHashResponse) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{26}
}

func (x *RootHashResponse) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

type InclusionProofRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InclusionProofRequest) Reset() {
	*x = InclusionProofRequest{}
	mi := &file_proto_arxdb_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InclusionProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InclusionProofRequest) ProtoMessage() {}

func (x *InclusionProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InclusionProofRequest.ProtoReflect.Descriptor instead.
func (*InclusionProofRequest) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{27}
}

func (x *InclusionProofRequest) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type InclusionProofResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeafHash      []byte                 `protobuf:"bytes,1,opt,name=leaf_hash,json=leafHash,proto3" json:"leaf_hash,omitempty"`
	Index         int64                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Path          [][]byte               `protobuf:"bytes,3,rep,name=path,proto3" json:"path,omitempty"` // sibling hashes, bottom-up
	Found         bool                   `protobuf:"varint,4,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InclusionProofResponse) Reset() {
	*x = InclusionProofResponse{}
	mi := &file_proto_arxdb_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InclusionProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InclusionProofResponse) ProtoMessage() {}

func (x *InclusionProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InclusionProofResponse.ProtoReflect.Descriptor instead.
func (*InclusionProofResponse) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{28}
}

func (x *InclusionProofResponse) GetLeafHash() []byte {
	if x != nil {
		return x.LeafHash
	}
	return nil
}

func (x *InclusionProofResponse) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *InclusionProofResponse) GetPath() [][]byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *InclusionProofResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type LenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LenRequest) Reset() {
	*x = LenRequest{}
	mi := &file_proto_arxdb_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LenRequest) ProtoMessage() {}

func (x *LenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LenRequest.ProtoReflect.Descriptor instead.
func (*LenRequest) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{29}
}

type LenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LenResponse) Reset() {
	*x = LenResponse{}
	mi := &file_proto_arxdb_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LenResponse) ProtoMessage() {}

func (x *LenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LenResponse.ProtoReflect.Descriptor instead.
func (*LenResponse) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{30}
}

func (x *LenResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CommitEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Premises      [][]byte               `protobuf:"bytes,1,rep,name=premises,proto3" json:"premises,omitempty"`
	Conclusion    []byte                 `protobuf:"bytes,2,opt,name=conclusion,proto3" json:"conclusion,omitempty"`
	EdgeData      []byte                 `protobuf:"bytes,3,opt,name=edge_data,json=edgeData,proto3" json:"edge_data,omitempty"`
	Proof         []byte                 `protobuf:"bytes,4,opt,name=proof,proto3,oneof" json:"proof,omitempty"` // absent == None (distinct from empty bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitEdgeRequest) Reset() {
	*x = CommitEdgeRequest{}
	mi := &file_proto_arxdb_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitEdgeRequest) ProtoMessage() {}

func (x *CommitEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitEdgeRequest.ProtoReflect.Descriptor instead.
func (*CommitEdgeRequest) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{31}
}

func (x *CommitEdgeRequest) GetPremises() [][]byte {
	if x != nil {
		return x.Premises
	}
	return nil
}

func (x *CommitEdgeRequest) GetConclusion() []byte {
	if x != nil {
		return x.Conclusion
	}
	return nil
}

func (x *CommitEdgeRequest) GetEdgeData() []byte {
	if x != nil {
		return x.EdgeData
	}
	return nil
}

func (x *CommitEdgeRequest) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

type CommitEdgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeHash      []byte                 `protobuf:"bytes,1,opt,name=edge_hash,json=edgeHash,proto3" json:"edge_hash,omitempty"`
	Entry         *LogEntry              `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitEdgeResponse) Reset() {
	*x = CommitEdgeResponse{}
	mi := &file_proto_arxdb_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitEdgeResponse) ProtoMessage() {}

func (x *CommitEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arxdb_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitEdgeResponse.ProtoReflect.Descriptor instead.
func (*CommitEdgeResponse) Descriptor() ([]byte, []int) {
	return file_proto_arxdb_proto_rawDescGZIP(), []int{32}
}

func (x *CommitEdgeResponse) GetEdgeHash() []byte {
	if x != nil {
		return x.EdgeHash
	}
	return nil
}

func (x *CommitEdgeResponse) GetEntry() *LogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

var File_proto_arxdb_proto protoreflect.FileDescriptor

const file_proto_arxdb_proto_rawDesc = "" +
	"\n" +
	"\x11proto/arxdb.proto\x12\x05arxdb\"&\n" +
	"\x10PutObjectRequest\x12\x12\n" +
	"\x04data\x18\x01 \x03(\fR\x04data\"+\n" +
	"\x11PutObjectResponse\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\fR\x06hashes\"*\n" +
	"\x10GetObjectRequest\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\fR\x06hashes\"=\n" +
	"\x11GetObjectResponse\x12\x12\n" +
	"\x04data\x18\x01 \x03(\fR\x04data\x12\x14\n" +
	"\x05found\x18\x02 \x03(\bR\x05found\"*\n" +
	"\x10HasObjectRequest\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\fR\x06hashes\")\n" +
	"\x11HasObjectResponse\x12\x14\n" +
	"\x05found\x18\x01 \x03(\bR\x05found\"2\n" +
	"\x13RegisterNodeRequest\x12\x1b\n" +
	"\tnode_hash\x18\x01 \x01(\fR\bnodeHash\"\x16\n" +
	"\x14RegisterNodeResponse\"n\n" +
	"\x13RegisterEdgeRequest\x12\x1b\n" +
	"\tedge_hash\x18\x01 \x01(\fR\bedgeHash\x12\x1a\n" +
	"\bpremises\x18\x02 \x03(\fR\bpremises\x12\x1e\n" +
	"\n" +
	"conclusion\x18\x03 \x01(\fR\n" +
	"conclusion\"\x16\n" +
	"\x14RegisterEdgeResponse\"5\n" +
	"\x16GetConnectivityRequest\x12\x1b\n" +
	"\tedge_hash\x18\x01 \x01(\fR\bedgeHash\"k\n" +
	"\x17GetConnectivityResponse\x12\x1a\n" +
	"\bpremises\x18\x01 \x03(\fR\bpremises\x12\x1e\n" +
	"\n" +
	"conclusion\x18\x02 \x01(\fR\n" +
	"conclusion\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"3\n" +
	"\x14IncomingEdgesRequest\x12\x1b\n" +
	"\tnode_hash\x18\x01 \x01(\fR\bnodeHash\"8\n" +
	"\x15IncomingEdgesResponse\x12\x1f\n" +
	"\vedge_hashes\x18\x01 \x03(\fR\n" +
	"edgeHashes\"3\n" +
	"\x14OutgoingEdgesRequest\x12\x1b\n" +
	"\tnode_hash\x18\x01 \x01(\fR\bnodeHash\"8\n" +
	"\x15OutgoingEdgesResponse\x12\x1f\n" +
	"\vedge_hashes\x18\x01 \x03(\fR\n" +
	"edgeHashes\"\x11\n" +
	"\x0fAllNodesRequest\"3\n" +
	"\x10AllNodesResponse\x12\x1f\n" +
	"\vnode_hashes\x18\x01 \x03(\fR\n" +
	"nodeHashes\"\x11\n" +
	"\x0fAllEdgesRequest\"3\n" +
	"\x10AllEdgesResponse\x12\x1f\n" +
	"\vedge_hashes\x18\x01 \x03(\fR\n" +
	"edgeHashes\"\xdf\x01\n" +
	"\bLogEntry\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x03R\vtimestampNs\x12#\n" +
	"\rsigner_pubkey\x18\x03 \x01(\fR\fsignerPubkey\x12\x1d\n" +
	"\n" +
	"entry_hash\x18\x04 \x01(\fR\tentryHash\x12\"\n" +
	"\rprev_log_hash\x18\x05 \x01(\fR\vprevLogHash\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\"%\n" +
	"\rAppendRequest\x12\x14\n" +
	"\x05entry\x18\x01 \x01(\fR\x05entry\"7\n" +
	"\x0eAppendResponse\x12%\n" +
	"\x05entry\x18\x01 \x01(\v2\x0f.arxdb.LogEntryR\x05entry\"#\n" +
	"\x0fGetEntryRequest\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\"O\n" +
	"\x10GetEntryResponse\x12%\n" +
	"\x05entry\x18\x01 \x01(\v2\x0f.arxdb.LogEntryR\x05entry\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x11\n" +
	"\x0fRootHashRequest\"/\n" +
	"\x10RootHashResponse\x12\x1b\n" +
	"\troot_hash\x18\x01 \x01(\fR\brootHash\")\n" +
	"\x15InclusionProofRequest\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\"u\n" +
	"\x16InclusionProofResponse\x12\x1b\n" +
	"\tleaf_hash\x18\x01 \x01(\fR\bleafHash\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x03R\x05index\x12\x12\n" +
	"\x04path\x18\x03 \x03(\fR\x04path\x12\x14\n" +
	"\x05found\x18\x04 \x01(\bR\x05found\"\f\n" +
	"\n" +
	"LenRequest\"#\n" +
	"\vLenResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"\x91\x01\n" +
	"\x11CommitEdgeRequest\x12\x1a\n" +
	"\bpremises\x18\x01 \x03(\fR\bpremises\x12\x1e\n" +
	"\n" +
	"conclusion\x18\x02 \x01(\fR\n" +
	"conclusion\x12\x1b\n" +
	"\tedge_data\x18\x03 \x01(\fR\bedgeData\x12\x19\n" +
	"\x05proof\x18\x04 \x01(\fH\x00R\x05proof\x88\x01\x01B\b\n" +
	"\x06_proof\"X\n" +
	"\x12CommitEdgeResponse\x12\x1b\n" +
	"\tedge_hash\x18\x01 \x01(\fR\bedgeHash\x12%\n" +
	"\x05entry\x18\x02 \x01(\v2\x0f.arxdb.LogEntryR\x05entry2\xb7\b\n" +
	"\x0eStorageService\x12>\n" +
	"\tPutObject\x12\x17.arxdb.PutObjectRequest\x1a\x18.arxdb.PutObjectResponse\x12>\n" +
	"\tGetObject\x12\x17.arxdb.GetObjectRequest\x1a\x18.arxdb.GetObjectResponse\x12>\n" +
	"\tHasObject\x12\x17.arxdb.HasObjectRequest\x1a\x18.arxdb.HasObjectResponse\x12G\n" +
	"\fRegisterNode\x12\x1a.arxdb.RegisterNodeRequest\x1a\x1b.arxdb.RegisterNodeResponse\x12G\n" +
	"\fRegisterEdge\x12\x1a.arxdb.RegisterEdgeRequest\x1a\x1b.arxdb.RegisterEdgeResponse\x12P\n" +
	"\x0fGetConnectivity\x12\x1d.arxdb.GetConnectivityRequest\x1a\x1e.arxdb.GetConnectivityResponse\x12J\n" +
	"\rIncomingEdges\x12\x1b.arxdb.IncomingEdgesRequest\x1a\x1c.arxdb.IncomingEdgesResponse\x12J\n" +
	"\rOutgoingEdges\x12\x1b.arxdb.OutgoingEdgesRequest\x1a\x1c.arxdb.OutgoingEdgesResponse\x12;\n" +
	"\bAllNodes\x12\x16.arxdb.AllNodesRequest\x1a\x17.arxdb.AllNodesResponse\x12;\n" +
	"\bAllEdges\x12\x16.arxdb.AllEdgesRequest\x1a\x17.arxdb.AllEdgesResponse\x125\n" +
	"\x06Append\x12\x14.arxdb.AppendRequest\x1a\x15.arxdb.AppendResponse\x12;\n" +
	"\bGetEntry\x12\x16.arxdb.GetEntryRequest\x1a\x17.arxdb.GetEntryResponse\x12;\n" +
	"\bRootHash\x12\x16.arxdb.RootHashRequest\x1a\x17.arxdb.RootHashResponse\x12M\n" +
	"\x0eInclusionProof\x12\x1c.arxdb.InclusionProofRequest\x1a\x1d.arxdb.InclusionProofResponse\x12,\n" +
	"\x03Len\x12\x11.arxdb.LenRequest\x1a\x12.arxdb.LenResponse\x12A\n" +
	"\n" +
	"CommitEdge\x12\x18.arxdb.CommitEdgeRequest\x1a\x19.arxdb.CommitEdgeResponseB0Z.github.com/larklaflamme/arxdb/go/proto/arxdbpbb\x06proto3"

var (
	file_proto_arxdb_proto_rawDescOnce sync.Once
	file_proto_arxdb_proto_rawDescData []byte
)

func file_proto_arxdb_proto_rawDescGZIP() []byte {
	file_proto_arxdb_proto_rawDescOnce.Do(func() {
		file_proto_arxdb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_arxdb_proto_rawDesc), len(file_proto_arxdb_proto_rawDesc)))
	})
	return file_proto_arxdb_proto_rawDescData
}

var file_proto_arxdb_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_proto_arxdb_proto_goTypes = []any{
	(*PutObjectRequest)(nil),        // 0: arxdb.PutObjectRequest
	(*PutObjectResponse)(nil),       // 1: arxdb.PutObjectResponse
	(*GetObjectRequest)(nil),        // 2: arxdb.GetObjectRequest
	(*GetObjectResponse)(nil),       // 3: arxdb.GetObjectResponse
	(*HasObjectRequest)(nil),        // 4: arxdb.HasObjectRequest
	(*HasObjectResponse)(nil),       // 5: arxdb.HasObjectResponse
	(*RegisterNodeRequest)(nil),     // 6: arxdb.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),    // 7: arxdb.RegisterNodeResponse
	(*RegisterEdgeRequest)(nil),     // 8: arxdb.RegisterEdgeRequest
	(*RegisterEdgeResponse)(nil),    // 9: arxdb.RegisterEdgeResponse
	(*GetConnectivityRequest)(nil),  // 10: arxdb.GetConnectivityRequest
	(*GetConnectivityResponse)(nil), // 11: arxdb.GetConnectivityResponse
	(*IncomingEdgesRequest)(nil),    // 12: arxdb.IncomingEdgesRequest
	(*IncomingEdgesResponse)(nil),   // 13: arxdb.IncomingEdgesResponse
	(*OutgoingEdgesRequest)(nil),    // 14: arxdb.OutgoingEdgesRequest
	(*OutgoingEdgesResponse)(nil),   // 15: arxdb.OutgoingEdgesResponse
	(*AllNodesRequest)(nil),         // 16: arxdb.AllNodesRequest
	(*AllNodesResponse)(nil),        // 17: arxdb.AllNodesResponse
	(*AllEdgesRequest)(nil),         // 18: arxdb.AllEdgesRequest
	(*AllEdgesResponse)(nil),        // 19: arxdb.AllEdgesResponse
	(*LogEntry)(nil),                // 20: arxdb.LogEntry
	(*AppendRequest)(nil),           // 21: arxdb.AppendRequest
	(*AppendResponse)(nil),          // 22: arxdb.AppendResponse
	(*GetEntryRequest)(nil),         // 23: arxdb.GetEntryRequest
	(*GetEntryResponse)(nil),        // 24: arxdb.GetEntryResponse
	(*RootHashRequest)(nil),         // 25: arxdb.RootHashRequest
	(*RootHashResponse)(nil),        // 26: arxdb.RootHashResponse
	(*InclusionProofRequest)(nil),   // 27: arxdb.InclusionProofRequest
	(*InclusionProofResponse)(nil),  // 28: arxdb.InclusionProofResponse
	(*LenRequest)(nil),              // 29: arxdb.LenRequest
	(*LenResponse)(nil),             // 30: arxdb.LenResponse
	(*CommitEdgeRequest)(nil),       // 31: arxdb.CommitEdgeRequest
	(*CommitEdgeResponse)(nil),      // 32: arxdb.CommitEdgeResponse
}
var file_proto_arxdb_proto_depIdxs = []int32{
	20, // 0: arxdb.AppendResponse.entry:type_name -> arxdb.LogEntry
	20, // 1: arxdb.GetEntryResponse.entry:type_name -> arxdb.LogEntry
	20, // 2: arxdb.CommitEdgeResponse.entry:type_name -> arxdb.LogEntry
	0,  // 3: arxdb.StorageService.PutObject:input_type -> arxdb.PutObjectRequest
	2,  // 4: arxdb.StorageService.GetObject:input_type -> arxdb.GetObjectRequest
	4,  // 5: arxdb.StorageService.HasObject:input_type -> arxdb.HasObjectRequest
	6,  // 6: arxdb.StorageService.RegisterNode:input_type -> arxdb.RegisterNodeRequest
	8,  // 7: arxdb.StorageService.RegisterEdge:input_type -> arxdb.RegisterEdgeRequest
	10, // 8: arxdb.StorageService.GetConnectivity:input_type -> arxdb.GetConnectivityRequest
	12, // 9: arxdb.StorageService.IncomingEdges:input_type -> arxdb.IncomingEdgesRequest
	14, // 10: arxdb.StorageService.OutgoingEdges:input_type -> arxdb.OutgoingEdgesRequest
	16, // 11: arxdb.StorageService.AllNodes:input_type -> arxdb.AllNodesRequest
	18, // 12: arxdb.StorageService.AllEdges:input_type -> arxdb.AllEdgesRequest
	21, // 13: arxdb.StorageService.Append:input_type -> arxdb.AppendRequest
	23, // 14: arxdb.StorageService.GetEntry:input_type -> arxdb.GetEntryRequest
	25, // 15: arxdb.StorageService.RootHash:input_type -> arxdb.RootHashRequest
	27, // 16: arxdb.StorageService.InclusionProof:input_type -> arxdb.InclusionProofRequest
	29, // 17: arxdb.StorageService.Len:input_type -> arxdb.LenRequest
	31, // 18: arxdb.StorageService.CommitEdge:input_type -> arxdb.CommitEdgeRequest
	1,  // 19: arxdb.StorageService.PutObject:output_type -> arxdb.PutObjectResponse
	3,  // 20: arxdb.StorageService.GetObject:output_type -> arxdb.GetObjectResponse
	5,  // 21: arxdb.StorageService.HasObject:output_type -> arxdb.HasObjectResponse
	7,  // 22: arxdb.StorageService.RegisterNode:output_type -> arxdb.RegisterNodeResponse
	9,  // 23: arxdb.StorageService.RegisterEdge:output_type -> arxdb.RegisterEdgeResponse
	11, // 24: arxdb.StorageService.GetConnectivity:output_type -> arxdb.GetConnectivityResponse
	13, // 25: arxdb.StorageService.IncomingEdges:output_type -> arxdb.IncomingEdgesResponse
	15, // 26: arxdb.StorageService.OutgoingEdges:output_type -> arxdb.OutgoingEdgesResponse
	17, // 27: arxdb.StorageService.AllNodes:output_type -> arxdb.AllNodesResponse
	19, // 28: arxdb.StorageService.AllEdges:output_type -> arxdb.AllEdgesResponse
	22, // 29: arxdb.StorageService.Append:output_type -> arxdb.AppendResponse
	24, // 30: arxdb.StorageService.GetEntry:output_type -> arxdb.GetEntryResponse
	26, // 31: arxdb.StorageService.RootHash:output_type -> arxdb.RootHashResponse
	28, // 32: arxdb.StorageService.InclusionProof:output_type -> arxdb.InclusionProofResponse
	30, // 33: arxdb.StorageService.Len:output_type -> arxdb.LenResponse
	32, // 34: arxdb.StorageService.CommitEdge:output_type -> arxdb.CommitEdgeResponse
	19, // [19:35] is the sub-list for method output_type
	3,  // [3:19] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_arxdb_proto_init() }
func file_proto_arxdb_proto_init() {
	if File_proto_arxdb_proto != nil {
		return
	}
	file_proto_arxdb_proto_msgTypes[31].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_arxdb_proto_rawDesc), len(file_proto_arxdb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_arxdb_proto_goTypes,
		DependencyIndexes: file_proto_arxdb_proto_depIdxs,
		MessageInfos:      file_proto_arxdb_proto_msgTypes,
	}.Build()
	File_proto_arxdb_proto = out.File
	file_proto_arxdb_proto_goTypes = nil
	file_proto_arxdb_proto_depIdxs = nil
}
